openapi: 3.0.3
info:
  title: AIoT Device Manager API
  version: 0.1.0
  description: |
    Minimal API for receiving sensor readings authenticated via Firebase.
servers:
  - url: http://localhost:4000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /api/sensors/data:
    post:
      summary: Store sensor reading
      security:
        - firebaseAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - deviceId
                - payload
              properties:
                deviceId:
                  type: string
                deviceName:
                  type: string
                recordedAt:
                  type: string
                  format: date-time
                payload:
                  type: object
                  additionalProperties: true
      responses:
        '201':
          description: Sensor reading stored
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Sensor reading stored
        '400':
          description: Validation error
        '401':
          description: Invalid or missing Firebase token
components:
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
